<a href="https://colab.research.google.com/github/Memo28/100DayofML/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
 import numpy as np

In [0]:
a = np.array([10, 20, 24, 5, 15, 50, 20, 24, 5, 15, 50])

In [9]:
a[3:]

array([ 5, 15, 50, 20, 24,  5, 15, 50])

In [10]:
a[3:7]

array([ 5, 15, 50, 20])

In [13]:
# Print alternating each 4 elements
a[::2]

array([10, 24, 15, 20,  5, 50])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
# Array of 4 row and 5 colums
ones = np.ones((4, 5))

ones 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
type(ones)

numpy.ndarray

In [19]:
type(ones[3][0])

numpy.float64

In [22]:
# Array con 5 elementos en y los valores estan entre 3 y 10
np.linspace(3, 50, 5)

array([ 3.  , 14.75, 26.5 , 38.25, 50.  ])

In [26]:
b = np.array([['x', 'y', 'z'], ['x', 'y', 'z']])
print(b)
type(b)

[['x' 'y' 'z']
 ['x' 'y' 'z']]


numpy.ndarray

In [29]:
# Devuelve el numero de dimensiones del arreglo
b.ndim

2

In [30]:
c = [12, 4, 10, 40, 2]
np.sort(c)

array([ 2,  4, 10, 12, 40])

In [33]:
# Nombre del parametro de cabecera y el dtype que sera
cabeceras = [("nombre", "S10"), ("edad", int)]
datos = [('Juan', 10), ('Miguel', 30), ('Tono', 80), ('Rodrigo', 15)]

# Creamos un nuevo arreglo con las cebeceras y los datos
usuarios = np.array(datos, dtype= cabeceras)

usuarios


array([(b'Juan', 10), (b'Miguel', 30), (b'Tono', 80), (b'Rodrigo', 15)],
      dtype=[('nombre', 'S10'), ('edad', '<i8')])

In [55]:
# Ordenar el arreglo por edad
np.sort(usuarios, order='nombre')

array([(b'Juan', 10), (b'Miguel', 30), (b'Rodrigo', 15), (b'Tono', 80)],
      dtype=[('nombre', 'S10'), ('edad', '<i8')])

In [42]:
# Crear un arreglo que inicie en 5 y se detanga en 50 con saltos de 7, tambien se puede ocupara para generar un array con x numero de elementos np.arange(10) -> crea un array con numeros del 0 al 9
np.arange(start = 5, stop = 50, step = 7)

array([ 5, 12, 19, 26, 33, 40, 47])

In [51]:
# Crear un arreglo o matriz y lo llena con el numero que se le pase como segundo parametro 
np.full((3, 2), 5)

array([[5, 5],
       [5, 5],
       [5, 5]])

In [54]:
# Crea una matriz diagonal con los numeros que se les pase en la diagonal
np.diag([6, 8, 0, 10, 9])

array([[ 6,  0,  0,  0,  0],
       [ 0,  8,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0, 10,  0],
       [ 0,  0,  0,  0,  9]])

In [56]:
cabeceras = [('Nombre', 'S10'), ('Edad', int), ('Pais', 'S10')]
datos = [('Miguel', 18, 'Mexico'), ('Arturo', 65, 'Peru'), ('Rocio', 10, 'Tunez'), ('Amber', 8, 'Rusia')]

usuarios = np.array(datos, dtype= cabeceras)
usuarios

array([(b'Miguel', 18, b'Mexico'), (b'Arturo', 65, b'Peru'),
       (b'Rocio', 10, b'Tunez'), (b'Amber',  8, b'Rusia')],
      dtype=[('Nombre', 'S10'), ('Edad', '<i8'), ('Pais', 'S10')])

In [57]:
np.sort(usuarios, order='Pais')

array([(b'Miguel', 18, b'Mexico'), (b'Arturo', 65, b'Peru'),
       (b'Amber',  8, b'Rusia'), (b'Rocio', 10, b'Tunez')],
      dtype=[('Nombre', 'S10'), ('Edad', '<i8'), ('Pais', 'S10')])